name: Update FAQ from Spreadsheet

on:
  schedule:
    - cron: '0 2 * * *'  # 毎日午前2時（JSTで午前11時）に実行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 リポジトリをクローン
        uses: actions/checkout@v3

      - name: 🐍 Pythonをセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 🔧 依存パッケージをインストール
        run: pip install -r requirements.txt

      - name: 📝 スプレッドシートから data/faq.json を生成
        run: python update_faq.py
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}

      - name: ✅ 差分があるか確認
        id: git-check
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/faq.json
          if git diff --cached --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: 🔁 最新を pull（競合回避）
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git pull origin main --no-rebase --allow-unrelated-histories || true

      - name: 🚀 変更がある場合はコミット＆プッシュ
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git pull --rebase origin main
          git commit -m "🤖 Update data/faq.json from spreadsheet"
          git push

      - name: 🚀 RenderにWebhookでデプロイを通知
        if: steps.git-check.outputs.changed == 'true'
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
