name: Update FAQ from Spreadsheet

on:
  workflow_dispatch:  # 手動実行を許可
  schedule:
    - cron: '0 18 * * 0'  # 毎週月曜03:00 JST（UTC日曜18:00）

jobs:
  update-faq:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Python をセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 依存パッケージをインストール
        run: pip install -r requirements.txt

      - name: スプレッドシートから JSON ファイルを生成
        run: python update_faq.py
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: faq.json をコミット・プッシュ（変更があった場合のみ）
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/faq.json
          git diff --cached --quiet || git commit -m "📄 update faq.json from spreadsheet"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
