name: Update faq.json and FAISS index

on:
  schedule:
    - cron: '0 18 * * 0'  # JST月曜03:00（UTC日曜18:00）
  workflow_dispatch:

jobs:
  update-faq:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Write credentials.json
        run: echo '${{ secrets.GOOGLE_CREDENTIALS_JSON }}' > credentials.json

      - name: Run update_faq_and_rebuild.py
        run: python update_faq_and_rebuild.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Commit and push updated files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data/faq.json data/vector_data.npy data/index.faiss
          git diff --cached --quiet || git commit -m "🗓️ Auto update faq.json and FAISS index"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
