name: Update FAQ JSON

on:
  schedule:
    - cron: '0 0 * * *'  # 毎日0時（UTC）＝日本時間9:00
  workflow_dispatch:

jobs:
  update_faq:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Decode credentials.json
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" | base64 -d > credentials.json

      - name: Run update_faq.py
        run: python update_faq.py

      - name: Commit and push updated faq_data.json
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add faq_data.json
          git commit -m "Update FAQ JSON" || echo "No changes to commit"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
