name: Update FAQ JSON

on:
  schedule:
    - cron: '0 0 * * *'  # UTCの0時 → JSTの9時

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Decode credentials.json
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" | base64 -d > credentials.json

      - name: Run update script
        run: python update_faq_json.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add faq_data.json
          git commit -m "Update FAQ JSON" || echo "No changes to commit"
          git push
