name: Update faq.json and FAISS index

on:
  schedule:
    - cron: '0 18 * * 0'  # JST月曜03:00（UTC日曜18:00）
  workflow_dispatch:

permissions:
  contents: write  # ✅ GITHUB_TOKEN に push 権限を明示的に付与

concurrency:
  group: update-faq
  cancel-in-progress: true

jobs:
  update-faq:
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install faiss-cpu python-dotenv

      - name: Write credentials.json
        run: echo '${{ secrets.GOOGLE_CREDENTIALS_JSON }}' > credentials.json

      - name: Run update_faq_and_rebuild.py
        run: python update_faq_and_rebuild.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Commit and push updated files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/faq.json data/vector_data.npy data/index.faiss
          git diff --cached --quiet || git commit -m "🗓️ Auto update faq.json and FAISS index"
          git push
